{% set name = "ndcube" %}
{% set version = "1.2.1" %}
{% set sha256 = "a5d908a93a7a2f856416d30ae2262e264a585f85da62d2e0cb46e7c34a28594c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt

requirements:
  build:
    - python >3
    - setuptools
    - setuptools_scm

  run:
    - python >3
    - astropy
    - matplotlib
    - sunpy >=1.0.3

test:
  requires:
    - pytest-astropy
    
  imports:
    - ndcube
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests
    
  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: 'LICENSE.rst'
  summary: 'A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.'
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - SolarDrew
    - Cadair
    - DanRyanIrish
