{% set name = "ndcube" %}
{% set version = "2.0.3" %}
{% set sha256 = "8d2ccc4fedb68d5840d255d4bebfb25d04373b80ac280f4be80efc397e3b608f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.7
    - astropy >=4.2
    - gwcs >=0.15
    - matplotlib-base >=3.2
    - mpl_animators >=1.0
    - numpy >1.17

test:
  requires:
    - pytest-astropy
    - pytest-mpl >=0.12
    - sunpy
    - reproject >=0.7.1

  imports:
    - ndcube
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
