{% set name = "ndcube" %}
{% set version = "2.2.4" %}
{% set sha256 = "43cef0d75f501445cbae19a593cefb8c10ef0796deca3fb661f1be3808b68422" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.10
    - astropy >=5.0
    - gwcs >=0.18
    - matplotlib-base >=3.5.0
    - mpl_animators >=1.0
    - numpy >1.23

test:
  requires:
    - dask >=2022.5.2
    - pytest >=7.1.0
    - pytest-astropy >=0.11.0
    - pytest-mpl >=0.12
    - scipy >=1.8.0
    - sunpy>=5.0.0
    - reproject >=0.7.1
    - specutils >=1.7.0

  imports:
    - ndcube
    - ndcube.extra_coords
    - ndcube.extra_coords.tests
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
