{% set name = "ndcube" %}
{% set version = "2.1.0" %}
{% set sha256 = "c77012ab9a4e927d6e0c8e72c9033075f9215968c6c09ec861a12ef9e14d8a9a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.8
    - astropy >=4.2
    - gwcs >=0.15
    - matplotlib-base >=3.2
    - mpl_animators >=1.0
    - numpy >1.17

test:
  requires:
    - dask
    - pytest
    - pytest-astropy
    - pytest-mpl >=0.12
    - scipy
    - sunpy>=4.0.0
    - reproject >=0.7.1

  imports:
    - ndcube
    - ndcube.extra_coords
    - ndcube.extra_coords.tests
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
