{% set name = "ndcube" %}

{% set version = "2.4.0rc1" %}
{% set sha256 = "cfd488d7e30890343e8246ccc35227d7583228632ffb33005574809278f0538f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - astropy-base >=6.1
    - gwcs >=0.21
    - numpy >=1.26
    - scipy >=1.12
    - matplotlib-base >=3.9.0
    - mpl_animators >=1.2

test:
  requires:
    - python {{ python_min }}
    - dask >=2024.1.0
    - pytest >=7.1.0
    - pytest-astropy >=0.11.0
    - pytest-mpl >=0.12
    - sunpy >=6.1.0
    - reproject >=0.14.0
    - specutils >=1.13.0
    - asdf >=3.1.0
    - asdf-astropy >=0.7.0

  imports:
    - ndcube
    - ndcube.extra_coords
    - ndcube.extra_coords.tests
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
