{% set name = "ndcube" %}
{% set version = "2.3.0rc1" %}
{% set sha256 = "843846ce005cd734835fd32eab2e20c81108e88ad448a50b1f3074b8864a8295" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - astropy-base >=5.0
    - gwcs >=0.18
    - matplotlib-base >=3.5.0
    - mpl_animators >=1.0
    - numpy >1.23

test:
  requires:
    - python {{ python_min }}
    - dask >=2022.5.2
    - pytest >=7.1.0
    - pytest-astropy >=0.11.0
    - pytest-mpl >=0.12
    - scipy >=1.8.0
    - sunpy>=5.0.0
    - reproject >=0.7.1
    - specutils >=1.7.0

  imports:
    - ndcube
    - ndcube.extra_coords
    - ndcube.extra_coords.tests
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
