{% set name = "ndcube" %}
{% set version = "1.1.3" %}
{% set sha256 = "8e663f62ce7092e215a7b46a9b6672c4850db80f424d8c16395c7ea2a0d4faf3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt

requirements:
  build:
    - python>3
    - setuptools
    - astropy

  run:
    - python>3
    - astropy<3.1
    - matplotlib
    - sunpy ==0.9

test:
  imports:
    - ndcube
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: 'LICENSE.rst'
  summary: 'A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.'
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - SolarDrew
    - Cadair
    - DanRyanIrish
